/**
 * AI provider integration test — no API key required.
 *
 * Boots a fake upstream that speaks the Hugging Face / OpenAI
 * `/chat/completions` wire format, then drives the real `LLMProvider` against
 * it. This covers what a unit test would miss: auth headers, URL construction,
 * JSON-mode negotiation, tolerant parsing, and — critically — that a provider
 * outage degrades to fallback output instead of throwing.
 *
 * Run with: npm run test:ai
 */
import http from 'http';

/** Records what the provider actually sent, and replies with canned data. */
const startFakeProvider = (port: number) =>
  new Promise<{ server: http.Server; seen: any[] }>((resolve) => {
    const seen: any[] = [];

    const server = http.createServer((req, res) => {
      let raw = '';
      req.on('data', (c) => (raw += c));
      req.on('end', () => {
        const payload = raw ? JSON.parse(raw) : {};
        seen.push({ url: req.url, auth: req.headers.authorization, payload });

        // Mimic a provider that rejects malformed requests.
        if (!payload.model || !Array.isArray(payload.messages)) {
          res.writeHead(400, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ error: { message: 'missing model or messages' } }));
          return;
        }

        // Respect `response_format` so we can prove JSON mode is negotiated.
        const wantsJson = payload.response_format?.type === 'json_object';
        const content = wantsJson
          ? JSON.stringify({
              ideas: [
                { title: 'Fake Idea One', hook: 'hook A', format: 'VIDEO', potentialScore: 91 },
                { title: 'Fake Idea Two', hook: 'hook B', format: 'SHORT', potentialScore: 88 },
              ],
              title: 'Fake Script',
              scenes: [{ sceneNumber: 1, visual: 'v', voiceover: 'vo', durationSec: 5 }],
              hookScore: 88,
              retentionScore: 90,
              clarityScore: 92,
              strengths: ['s'],
              weaknesses: ['w'],
              recommendations: ['r'],
            })
          : 'Generated by the fake provider.';

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(
          JSON.stringify({
            model: payload.model,
            choices: [{ message: { role: 'assistant', content } }],
            usage: { prompt_tokens: 120, completion_tokens: 60 },
          })
        );
      });
    });

    server.listen(port, () => resolve({ server, seen }));
  });

const results: { name: string; ok: boolean }[] = [];
const check = (name: string, cond: unknown, extra?: unknown) => {
  results.push({ name, ok: !!cond });
  console.log(`${cond ? 'PASS' : 'FAIL'}  ${name}${extra !== undefined ? `  :: ${extra}` : ''}`);
};

const run = async () => {
  const port = 5000 + Math.floor(Math.random() * 4000);
  const { server: fake, seen } = await startFakeProvider(port);

  // Must be set before importing the provider: `config` is evaluated at load.
  process.env.AI_PROVIDER = 'openai';
  process.env.AI_BASE_URL = `http://127.0.0.1:${port}/v1`;
  process.env.OPENAI_API_KEY = 'test-key-not-real';
  process.env.AI_MODEL = 'Qwen/Qwen2.5-7B-Instruct';

  const { aiProvider, parseJsonLoose } = await import('../ai/provider');

  check('provider resolved from env', aiProvider.name === 'openai', aiProvider.name);

  const ctx = { requestType: 'test', userId: null, workspaceId: null };

  /* --- prose endpoints (jsonMode disabled) ---------------------- */
  const caption = await aiProvider.generateCaption(
    { topic: 'AI', platform: 'YOUTUBE', tone: 'Direct' },
    ctx
  );
  check('generateCaption returns prose', caption === 'Generated by the fake provider.', caption);
  check('prose request omits response_format', seen[0]?.payload?.response_format === undefined);

  const cta = await aiProvider.generateCTA('Grow', 'YOUTUBE', ctx);
  check('generateCTA returns prose', typeof cta === 'string' && cta.length > 0, cta);

  /* --- structured endpoints (jsonMode negotiated) --------------- */
  const ideas = await aiProvider.generateIdeas('AI', 'tech', 'YOUTUBE', ctx);
  check('generateIdeas parsed JSON', Array.isArray(ideas) && ideas[0]?.title === 'Fake Idea One', ideas[0]?.title);

  const script = await aiProvider.generateScript(
    { topic: 'x', platform: 'YOUTUBE', tone: 'Direct', length: '60s' },
    ctx
  );
  check('generateScript parsed JSON', Array.isArray(script?.scenes), `scenes=${script?.scenes?.length}`);

  const analysis = await aiProvider.analyzeContent(
    { title: 't', type: 'VIDEO', views: 10, engagementRate: 5 },
    ctx
  );
  check('analyzeContent parsed JSON', analysis?.hookScore === 88, `hookScore=${analysis?.hookScore}`);

  const jsonReq = seen.find((s) => s.payload?.response_format?.type === 'json_object');
  check('JSON mode requested for structured calls', !!jsonReq, jsonReq?.url);

  /* --- request shape -------------------------------------------- */
  check('Authorization header sent', seen[0]?.auth === 'Bearer test-key-not-real', seen[0]?.auth);
  check('posts to /chat/completions', seen[0]?.url === '/v1/chat/completions', seen[0]?.url);
  check(
    'model id forwarded verbatim',
    seen[0]?.payload?.model === 'Qwen/Qwen2.5-7B-Instruct',
    seen[0]?.payload?.model
  );

  /* --- tolerant JSON parsing ------------------------------------- */
  check('parseJsonLoose strips ``` fences', (parseJsonLoose('```json\n{"a":1}\n```', {}) as any).a === 1);
  check('parseJsonLoose extracts embedded JSON', (parseJsonLoose('sure! {"a":2}', {}) as any).a === 2);
  check('parseJsonLoose returns fallback on prose', (parseJsonLoose('no json', { f: 1 }) as any).f === 1);
  check('parseJsonLoose handles arrays', Array.isArray(parseJsonLoose('```json\n["#a"]\n```', [])));

  /* --- graceful degradation -------------------------------------- */
  fake.close();
  await new Promise((r) => setTimeout(r, 150));

  const offlineCaption = await aiProvider.generateCaption(
    { topic: 'AI', platform: 'YOUTUBE', tone: 'Direct' },
    ctx
  );
  check(
    'provider outage falls back instead of throwing',
    typeof offlineCaption === 'string' && offlineCaption.length > 0,
    offlineCaption.slice(0, 40)
  );

  const offlineIdeas = await aiProvider.generateIdeas('AI', 'tech', 'YOUTUBE', ctx);
  check(
    'offline generateIdeas still returns a usable array',
    Array.isArray(offlineIdeas) && offlineIdeas.length > 0,
    `${offlineIdeas.length} ideas`
  );

  const failed = results.filter((r) => !r.ok);
  console.log(`\n${results.length - failed.length}/${results.length} checks passed`);
  if (failed.length) {
    console.log('failing:');
    for (const f of failed) console.log(`  - ${f.name}`);
  }
  process.exit(failed.length ? 1 : 0);
};

run().catch((e) => {
  console.error('AI integration test crashed:', e);
  process.exit(1);
});

