export function seedPart1(store: any) {
  store.adminUsers.push({
    id: 'adm_01',
    email: 'admin@creatoros.ai',
    name: 'CreatorOS System Admin',
    passwordHash: '$2a$10$wE26UvAonNl2.F68N3bXie4o2N4qE6u5T/9BwNl.YvL8xGk3Wqf9m',
    role: 'SUPER_ADMIN',
    createdAt: new Date().toISOString()
  });

  store.contents.push(
    {
      id: 'cnt_01',
      workspaceId: 'ws_main_01',
      socialAccountId: 'soc_yt',
      title: 'Building an AI Agent in 10 Minutes',
      description: 'Complete walkthrough on orchestrating multimodal agents.',
      caption: 'The future of autonomous workflows is here. #AI #Coding',
      type: 'VIDEO',
      platform: 'YOUTUBE',
      status: 'PUBLISHED',
      thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
      tags: ['AI', 'Tutorial', 'Automation'],
      views: 184500,
      likes: 14200,
      commentsCount: 940,
      shares: 3120,
      engagementRate: 8.8,
      watchTimeMinutes: 842000,
      publishedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString()
    },
    {
      id: 'cnt_02',
      workspaceId: 'ws_main_01',
      socialAccountId: 'soc_ig',
      title: '5 AI Tools Creators Must Use in 2026',
      description: 'Carousel breakdown of the top tools.',
      caption: '5 AI tools saving 20h/week! #CreatorTools',
      type: 'CAROUSEL',
      platform: 'INSTAGRAM',
      status: 'PUBLISHED',
      thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
      tags: ['Tools', 'Productivity'],
      views: 94200,
      likes: 8750,
      commentsCount: 620,
      shares: 4100,
      engagementRate: 14.3,
      watchTimeMinutes: 45000,
      publishedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      createdAt: new Date(Date.now() - 6 * 86400000).toISOString()
    },
    {
      id: 'cnt_03',
      workspaceId: 'ws_main_01',
      socialAccountId: 'soc_tt',
      title: 'Why Most Creators Fail in Month 3',
      description: 'Hard truth about retention curves.',
      caption: 'You do not need 4K cameras, you need retention. #creatoradvice',
      type: 'SHORT',
      platform: 'TIKTOK',
      status: 'PUBLISHED',
      thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
      tags: ['Shorts', 'Growth'],
      views: 420000,
      likes: 38200,
      commentsCount: 1840,
      shares: 11200,
      engagementRate: 12.2,
      watchTimeMinutes: 310000,
      publishedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString()
    },
    {
      id: 'cnt_04',
      workspaceId: 'ws_main_01',
      socialAccountId: 'soc_li',
      title: 'The Solopreneur AI Stack: 1 Person, 1M Revenue',
      description: 'Comprehensive essay on leveraging LLMs.',
      caption: 'The era of the solopreneur enterprise has arrived.',
      type: 'ARTICLE',
      platform: 'LINKEDIN',
      status: 'SCHEDULED',
      thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
      tags: ['Business', 'SaaS'],
      views: 0,
      likes: 0,
      commentsCount: 0,
      shares: 0,
      engagementRate: 0,
      watchTimeMinutes: 0,
      scheduledAt: new Date(Date.now() + 2 * 86400000).toISOString(),
      createdAt: new Date().toISOString()
    }
  );

  store.dnaList.push({
    id: 'dna_01',
    contentId: 'cnt_01',
    hook: 'Curiosity gap within 4.2 seconds',
    topic: 'Multimodal AI Agent Architecture',
    format: 'Technical Masterclass',
    tone: 'Authoritative, Practical',
    lengthSeconds: 684,
    keywords: ['AI agents', 'LLM orchestration', 'Python API'],
    cta: 'Download architecture template in description',
    targetAudience: 'Software Developers & Tech Creators',
    strengths: ['Exceptional first 30s retention', 'Zero dead space', 'Visual diagram overlays'],
    weaknesses: ['Jargon dip at 6:30', 'Rapid end CTA'],
    recommendations: ['Add code timestamps', 'Split into 3 vertical Shorts'],
    visualStyle: 'Modern Dark Studio with Cyan Code Overlays',
    score: 92
  });
}
